version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    restart: always

  redis-queue:
    image: redis:6.2-alpine
    restart: always

  redis-socketio:
    image: redis:6.2-alpine
    restart: always

  backend:
    image: frappe/frappe:version-15
    restart: always
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      SITE_NAME: erp.mysite.local
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  site-creator:
    image: frappe/frappe:version-15
    restart: "no"
    depends_on:
      - backend
    command: >
      bash -c "
        bench new-site erp.mysite.local --admin-password admin --mariadb-root-password root &&
        bench --site erp.mysite.local install-app erpnext &&
        echo 'site created'
      "
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  nginx:
    image: nginx:1.22-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  mariadb_data:
  sites:
