version: "3.7"

services:
  db:
    image: mariadb:10.6
    container_name: erpnext-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erpnet

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    networks:
      - erpnet

  redis-queue:
    image: redis:6.2-alpine
    container_name: redis-queue
    networks:
      - erpnet

  redis-socketio:
    image: redis:6.2-alpine
    container_name: redis-socketio
    networks:
      - erpnet

    backend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-backend
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    environment:
      SITE_NAME: site1.local
      DB_ROOT_PASSWORD: admin
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext
    entrypoint: >
  bash -c '
    if [ ! -f /home/frappe/frappe-bench/sites/site1.local/site_config.json ]; then
      export PATH=$PATH:/home/frappe/.local/bin &&
      cd /home/frappe/frappe-bench &&
      bench new-site site1.local --admin-password admin --mariadb-root-password admin --db-host db &&
      bench --site site1.local install-app erpnext;
    fi &&
    cd /home/frappe/frappe-bench && bench start
  '
    networks:
      - erpnet

  frontend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - erpnet

volumes:
  db_data:
  sites:

networks:
  erpnet:
    driver: bridge
