version: "3.7"

services:
  db:
    image: mariadb:10.6
    container_name: erpnext-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erpnet

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    networks:
      - erpnet

  redis-queue:
    image: redis:6.2-alpine
    container_name: redis-queue
    networks:
      - erpnet

  redis-socketio:
    image: redis:6.2-alpine
    container_name: redis-socketio
    networks:
      - erpnet

  backend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-backend
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      DB_ROOT_PASSWORD: admin
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext
    volumes:
      - sites:/home/frappe/frappe-bench/sites
   entrypoint: >
  bash -c "
    if [ ! -f /home/frappe/frappe-bench/sites/site1.local/site_config.json ]; then
      bench new-site site1.local \
        --admin-password admin \
        --db-root-password admin \
        --db-host erpnext-db && \
      bench --site site1.local install-app erpnext;
    fi && \
    bench start"
    networks:
      - erpnet

  frontend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - erpnet

volumes:
  db_data:
  sites:

networks:
  erpnet:
    driver: bridge
