version: "3.7"

services:
  db:
    image: mariadb:10.6
    container_name: erpnext-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erpnet

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    networks:
      - erpnet

  redis-queue:
    image: redis:6.2-alpine
    container_name: redis-queue
    networks:
      - erpnet

  redis-socketio:
    image: redis:6.2-alpine
    container_name: redis-socketio
    networks:
      - erpnet

  backend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-backend
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      SITE_NAME: site1.local
      DB_ROOT_PASSWORD: admin
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    entrypoint: >
      bash -c '
        export PATH=$PATH:/home/frappe/.local/bin;
        cd /home/frappe/frappe-bench;

        # Ensure Procfile exists
        if [ ! -f Procfile ]; then
          echo "web: bench serve --port 8000" > Procfile;
          echo "worker: bench worker" >> Procfile;
          echo "schedule: bench schedule" >> Procfile;
        fi;

        # Wait for the database to be ready
        until mysqladmin ping -h db --silent; do
          echo "Waiting for database to be ready...";
          sleep 5;
        done;

        # Create the site if it does not exist
        if [ ! -f sites/site1.local/site_config.json ]; then
          bench new-site site1.local \
            --admin-password admin \
            --mariadb-root-password admin \
            --db-host db \
            --no-mariadb-socket \
            --no-input &&
          bench --site site1.local install-app erpnext;
        fi;

        # Start the application
        bench start
      '
    networks:
      - erpnet

  frontend:
    image: frappe/erpnext:v15.58.2
    container_name: erpnext-frontend
    depends_on:
      - backend
    ports:
      - "8080:8000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - erpnet

volumes:
  db_data:
  sites:

networks:
  erpnet:
    driver: bridge
